# Generated by Django 3.1.7 on 2021-03-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image1', models.FileField(upload_to='service/')),
                ('image2', models.FileField(upload_to='service/')),
                ('feature1', models.CharField(blank=True, max_length=150, null=True)),
                ('feature2', models.CharField(blank=True, max_length=150, null=True)),
                ('feature3', models.CharField(blank=True, max_length=150, null=True)),
                ('feature4', models.CharField(blank=True, max_length=150, null=True)),
                ('feature5', models.CharField(blank=True, max_length=150, null=True)),
                ('feature6', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
