# Generated by Django 3.1.7 on 2021-03-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='service/')),
            ],
        ),
        migrations.CreateModel(
            name='serviceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image1', models.FileField(upload_to='service/')),
                ('image2', models.FileField(upload_to='service/')),
            ],
        ),
        migrations.DeleteModel(
            name='services',
        ),
    ]
