# Generated by Django 3.1.7 on 2021-03-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210309_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.service'),
        ),
    ]
