# Generated by Django 3.1.7 on 2021-03-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_serviceitem_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('image', models.FileField(upload_to='service/')),
                ('isVideo', models.BooleanField(default=False)),
                ('videoLink', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
