# Generated by Django 3.1.7 on 2021-03-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
